resources:
  - ../../base

namePrefix: dev-

images:
  - name: xllauca/uoc-tfm
    newName: docker.io/xllauca/uoc-tfm
    digest: sha256:3fbb6e6f2546b7fccbdbd6883268f4005d011952cffbaef07af0dc77931d0550

namespace: solar-system-dev