resources:
  - ../../base

namePrefix: dev-

images:
  - name: xllauca/uoc-tfm
    newName: xllauca/uoc-tfm
    digest: sha256:875dbe7603b140916098bc76413085327e29c6906e18f058a422dba432a0390a

namespace: solar-system-dev
