apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  labels:
    app: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        - name: solar-system
          image: docker.io/xllauca/uoc-tfm@sha256:3fbb6e6f2546b7fccbdbd6883268f4005d011952cffbaef07af0dc77931d0550
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
